[project]
name = "discordlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "emoji>=2.15.0",
    "numpy>=2.4.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
